# =========================
# Paramètres par listener
# =========================

per_listener_settings true


# =========================
# MQTT interne Docker
# =========================

listener 1883
allow_anonymous true


# =========================
# MQTT sécurisé
# =========================

listener 8883

cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key

tls_version tlsv1.2

allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl